version: '3'

services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - docker-vol:/var/lib/docker

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375
    depends_on:
      - dind

volumes:
  jenkins-home:
  docker-vol:
